server:
  port: 8080
  servlet:
    context-path: /coffee-store
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./database/coffee-store
    username: admin
    password: bestseller
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: false
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-ui
      settings:
        web-allow-others: true
